### ISSUE TITLE
Kerberos 5 Keytab support for iRODS HPSS Resource Plugin

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods_resource_plugin_hpss#1842]
The current implementation of the hpss resource plugin will only work with a unix keytab.

This is hard coded in the `hpss_SetLoginCred` call (`libhpss.cpp` lines 284-288)

```
int status = hpss_SetLoginCred( const_cast<char*>( user.c_str() ),
hpss_authn_mech_unix,
hpss_rpc_cred_client,
hpss_rpc_auth_type_keytab,
const_cast<char*>( keytab.c_str() ) );
```

I believe the `hpss_authn_mech_unix` is what's causing us problems.

This causes the plugin to fail for anyone using Kerberos5 and not unix keytabs (like us).

I've seen cases where
`hpss_Getenv("HPSS_PRIMARY_AUTHN_MECH");`
is used to allow the HPSS env to be the source of the authn_mechanism, thus allowing either unix or krb5 to be used/defined.

Can you modify the plugin to cover Kerberos5 as well please.

**Comment by johnalankennedy** [comment]
Just to give a bit more info

There is an example of how to use hpss_Getenv to set the Auth Mechanism in the HPSS Programmers Reference:

http://www.hpss-collaboration.org/documents/hpss741/progref.pdf

Have a look at page 38.

**Comment by johnalankennedy** [comment]
Following a period of trials - with support from Jason - I got this working.

From the HPSS programming manual I found that you can gain extra diagnostic info about authentication errors etc by touching the following files.

/var/hpss/tmp/gasapi.diag
/var/hpss/tmp/secapi.diag

(I did this on my irods server - so the client side from the HPSS perspective).

I noticed three errors:

(hpss_sec.c:1902)can't open /opt/hpss/lib/libhpsskrb5auth.so: /opt/hpss/lib/libhpsskrb5auth.so: undefined symbol: GAS_C_NT_HOSTBASED_SERVICE
(hpss_sec.c:1902)can't open /opt/hpss/lib/libhpssldapauthz.so: /opt/hpss/lib/libhpssldapauthz.so: cannot open shared object file: No such file or directory
(hpss_sec.c:1902)can't open /opt/hpss/lib/libhpssunixauth.so: /opt/hpss/lib/libhpssunixauth.so: undefined symbol: GAS_C_NT_EXPORT_NAME

The missing  /opt/hpss/lib/libhpssldapauthz.so doesn't seem to be a real problem.

But the other two errors were causing us problems.

I added the 
libhpsskrb5auth.so
libhpssunixauth.so

to the EXTRALIBS in the hpss Makefile

irods_resource_plugin_hpss/hpss/Makefile

EXTRALIBS = -lhpss \
            -lhpsscs \
            -lhpsskrb5auth \
            -lhpssunixauth \
            -lboost_filesystem-mt 

and re-made the driver lib.

This worked for me and I now have a working driver.
